#This workflow defines a DevSecOps pipeline that includes code quality checks, dependency scanning, secret scanning, Dockerfile scanning, building and pushing Docker images, scanning images with Trivy, and deploying the application on an EC2 instance. Each job is defined in separate workflow files for better modularity and maintainability.
name: DevSecOps-pipeline
on:
  workflow_dispatch:

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml

  dependency-scan:
    uses: ./.github/workflows/dependency-scan.yml

  secret-scan:
    uses: ./.github/workflows/secret-scan.yml
    secrets: inherit

  DockerFile_scan:
    uses: ./.github/workflows/dockerfile-scan.yml

  Build_and_push:
    needs: ["code-quality", "dependency-scan", "secret-scan", "DockerFile_scan"]
    uses: ./.github/workflows/docker-build-and-push.yml
    secrets: inherit

  Trivy_scan:
    needs: [Build_and_push]
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/dockerhub-image_scan.yml
    secrets: inherit

  Deploy_on_ec2:
    needs: [Trivy_scan]
    uses: ./.github/workflows/app-ec2-deploy.yml
    secrets: inherit
