name: intro_wrokflow
on:
  workflow_dispatch:
jobs:
  my_name:
    runs-on: ubuntu-latest
    steps:
      - name: what is ur name
        run: echo "My name is harsh choubey"
  qualification:
    runs-on: ubuntu-latest
    steps:
      - name: what is your quaalification
        run: echo "Currently i am pursuing my bachelor degree from NSIT"
  hobbies:
    runs-on: ubuntu-latest
    steps:
      - name: what are ur hobbies
        run: echo "My hoobies are coding,netflix,cricket" 
  goal: 
   runs-on: ubuntu-latest
   steps:
     - name: what are  your goals
     run: echo "i want to join MNC as a devops  engg."
